/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zhuaqu.ali1688.ui;

import java.awt.Toolkit;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import com.ydj.simpleSpider.MyLog;


/**
 * 
 * @author : Apple
 * @createTime : Aug 17, 2012 1:49:22 PM
 * @version : 1.0
 * @description :
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	/**文件夹选择*/
    private javax.swing.JFileChooser jfc = new javax.swing.JFileChooser(); 
	
	/**
     * Creates new form NewJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    private void initComponents() {

    	this.setTitle("抓 抓 抓...抓个蛋蛋");
    	
    	jTextField_host = new javax.swing.JComboBox();
        jLabel_host = new javax.swing.JLabel();
    	
        jTextField_userName = new javax.swing.JTextField();
        jLabel_userName = new javax.swing.JLabel();
       
        jLabel_password = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JPasswordField();
        
        
        jLabel_savePath = new javax.swing.JLabel();
        jTextField_savePath = new javax.swing.JTextField();
        
        jButton_browse = new javax.swing.JButton();
        
        jLabel_cookie = new javax.swing.JLabel();
		jTextField_cookie = new javax.swing.JTextField();
		
        jLabel_userAgent = new javax.swing.JLabel();
        jTextField_userAgent = new javax.swing.JTextField();
        
        
        jLabel_alertSet = new javax.swing.JLabel();
        jTextField_alertSet = new javax.swing.JComboBox();
        
        jLabel_frequencySet = new javax.swing.JLabel();
        jTextField_frequencySet = new javax.swing.JComboBox();
        
        
        jButton_connect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_host.setText("代理IP");
        jLabel_userName.setText("端         口");
        jLabel_password.setText("密         码");
        jLabel_userAgent.setText("设置UserAgent");
        jLabel_cookie.setText("设置Cookie");
        jLabel_alertSet.setText("失败N次时提醒");
        jLabel_frequencySet.setText("设置抓取的频率");
        jLabel_savePath.setText("保存目录");

        jTextField_savePath.setEditable(false);//设置不可以输入
        
        jButton_browse.setText("浏览");
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButton_Browse_ActionPerformed(evt);
            }
        });
        

        jButton_connect.setText("开始抓取");
        jButton_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectJButtonActionPerformed(evt);
            }
        });
        
        
        Object items[] = new Object[]{5,10,15,20,25,30,50,100,200}; 
        jTextField_alertSet.setModel(new javax.swing.DefaultComboBoxModel(items));
        
        
        Object items2[] = new Object[]{"500毫秒~1秒","1秒~3秒","1秒~5秒","2秒~6秒","6秒~10秒","20秒~30秒"}; 
        jTextField_frequencySet.setModel(new javax.swing.DefaultComboBoxModel(items2));
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_host)
                            .addComponent(jLabel_userName)
                            .addComponent(jLabel_password)
                            .addComponent(jLabel_cookie)
                            .addComponent(jLabel_userAgent)
                            .addComponent(jLabel_alertSet)
                            .addComponent(jLabel_frequencySet)
                            .addComponent(jLabel_savePath)
                            
                        		)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_host)
                            .addComponent(jTextField_userName)
                            .addComponent(jTextField_password)
                            .addComponent(jTextField_cookie)
                            .addComponent(jTextField_alertSet)
                            .addComponent(jTextField_frequencySet)
                            .addComponent(jTextField_savePath)
                            .addComponent(jTextField_userAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            
                        		)
                        		
                        		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        				.addComponent(jButton_browse, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            )
                        		
                    		)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton_connect)
                        
                    		))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_host)
                    .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_userName)
                    .addComponent(jTextField_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_userAgent)
                    .addComponent(jTextField_userAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    
                    
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cookie)
                    .addComponent(jTextField_cookie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_alertSet)
                    .addComponent(jTextField_alertSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_frequencySet)
                    .addComponent(jTextField_frequencySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_savePath)
                    .addComponent(jTextField_savePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_browse)) 
                    
                            
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton_connect)
                .addGap(24, 24, 24)
                
            	)
        );

        
        pack();
        
        this.setIconImage(Toolkit.getDefaultToolkit().createImage(MainJFrame.class.getResource("logo.png"))); 
        this.setResizable(false);//设置不可以最大化
        this.setLocationRelativeTo(null);
        
        this.setSize(500, 500);
    }
    
    
    private void jButton_Browse_ActionPerformed(java.awt.event.ActionEvent evt) {
    	jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);//设置只可以选择文件夹
        int state = jfc.showOpenDialog(null);
        if (state == 1) {  
            return;  
        } else {  
            File f = jfc.getSelectedFile();
            jTextField_savePath.setText(f.getAbsolutePath());  
        } 
    }
    
    /** 
     *二种不同实现方式 jButtonSelectPathActionPerformed
     */  
    public void actionPerformed(java.awt.event.ActionEvent e) {  
        if (e.getSource().equals(jButton_browse)) {
            jfc.setFileSelectionMode(1);
            int state = jfc.showOpenDialog(null);  
            if (state == 1) {  
                return;  
            } else {  
                File f = jfc.getSelectedFile();
                jTextField_savePath.setText(f.getAbsolutePath());  
            }  
        }
    } 
    
    

    private void connectJButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	
//    	Object host = this.jTextField_host.getSelectedItem();
//    	String userName = this.jTextField_userName.getText();
//    	String password = this.jTextField_password.getText();
    	
    	String cookie = this.jTextField_cookie.getText();
    	String userAgent = this.jTextField_userAgent.getText();
    	Object alertSet = jTextField_alertSet.getSelectedItem();
    	Object frequencySet = jTextField_frequencySet.getSelectedItem();
    	String savePath = jTextField_savePath.getText()+"/";  
    	
    	MyLog.logInfo("userAgent: "+userAgent);
    	MyLog.logInfo("cookie: "+cookie);
    	MyLog.logInfo("alertSet: "+alertSet.toString());
    	MyLog.logInfo("frequencySet: "+frequencySet.toString());
    	MyLog.logInfo("savePath: "+savePath);
    	

    	if(cookie == null || "".equals(cookie)){
    		JOptionPane.showMessageDialog(null, "请设置Cookie和UserAgent","提示",JOptionPane.ERROR_MESSAGE); 
    		return ;
    	}
    	
    	Common2.cookie = cookie;
    	
    	if(Common2.isNotEmpty(userAgent)){
    		Common2.userAgent = userAgent;
    	}
    	
    	SecondStep2.alertCount = Integer.parseInt(alertSet.toString());
    	SecondStep2.savePath = savePath;
    	
    	this.frequencySet(frequencySet.toString());

    	//TODO: 保存用户输入，缓存
    	
    	this.setVisible(false);
    	
    	final SecondStep2 spider = new SecondStep2();

    	ShowJFrame showJFrame = new ShowJFrame(spider);
    	showJFrame.setVisible(true);
    	
    	new Thread(
    			new Runnable() {
					
					@Override
					public void run() {
						try {
							spider.start();
						} catch (Exception e) {
							e.printStackTrace();
						}
					}
				}
    	).start();
    	
    	
    	
    	
    }
    
    
    private void frequencySet(String choose){
    	// "500毫秒~1秒","1秒~3秒","1秒~5秒","2秒~6秒","6秒~10秒","20秒~30秒"
    	
    	if("500毫秒~1秒".equals(choose)){
    		SecondStep2.frequencyMin = 500;
    		SecondStep2.frequencyMax = 1000;
    	}
    	
    	if("1秒~3秒".equals(choose)){
    		SecondStep2.frequencyMin = 1000;
    		SecondStep2.frequencyMax = 3000;
    	}
    	
    	if("1秒~5秒".equals(choose)){
    		SecondStep2.frequencyMin = 1000;
    		SecondStep2.frequencyMax = 5000;
    	}
    	
    	if("2秒~6秒".equals(choose)){
    		SecondStep2.frequencyMin = 2000;
    		SecondStep2.frequencyMax = 6000;
    	}
    	
    	if("6秒~10秒".equals(choose)){
    		SecondStep2.frequencyMin = 6000;
    		SecondStep2.frequencyMax = 10*1000;
    	}
    	
    	if("20秒~30秒".equals(choose)){
    		SecondStep2.frequencyMin = 20*1000;
    		SecondStep2.frequencyMax = 30*1000;
    	}
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    	
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_connect;
    private javax.swing.JLabel jLabel_host;
    private javax.swing.JLabel jLabel_userName;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_userAgent;
    private javax.swing.JLabel jLabel_cookie;
    private javax.swing.JLabel jLabel_alertSet;
    private javax.swing.JLabel jLabel_savePath;
    private javax.swing.JLabel jLabel_frequencySet;

    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jTextField_host;
    private javax.swing.JTextField jTextField_userName;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_userAgent;
    private javax.swing.JTextField jTextField_cookie;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jTextField_alertSet;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jTextField_frequencySet;
    private javax.swing.JTextField jTextField_savePath;
    
    private javax.swing.JButton jButton_browse;
    // End of variables declaration//GEN-END:variables
}
